### ISSUE TITLE
Encodage issue

### ISSUE THREAD

**Issue by thenew** [thierrylemoulec/Sublime-Csslisible#1]
Ne supporte pas les caractères spéciaux (é, ê, etc). Problème avec l'encodage UTF-8 ?

**Comment by thierrylemoulec** [comment]
En effet problème au niveau des caractères spéciaux due à l'encodage, l'API ne renvoyant pas dans la réponse un charset dans le headers 'content-type'. C'est réglé avec le dernier commit (thanks to the awesome requests http lib). De mon coté ça fonctionne maintenant. Package control devrait bientôt mettre à jour automatiquement.
