### ISSUE TITLE
2 raccourcis clavier pour 2 usages

### ISSUE THREAD

**Issue by NumEricR** [thierrylemoulec/Sublime-Csslisible#6]
Hello,

Un truc que j'ai en tête depuis quelques jours maintenant : ne serait-il pas possible d'avoir à disposition 2 raccourcis clavier pour ce package ?

En gros je vois 2 usages principaux : l'un pour nettoyer le code et l'autre pour créer une version compressée pour la prod. L'idée serait donc de garder le fonctionnement paramétrable actuel mais ajouter en plus un second raccourci clavier qui produirait par défaut le code compressé.

Le but ultime serait même de pouvoir générer le code compressé dans un nouvel onglet. On aurait alors 1 seul paramètre de configuration pour la compression.

_Je ne sais pas si cela est faisable :)_

**Comment by thierrylemoulec** [comment]
Salut @NumEricR 

C'est faisable en effet, cependant je ne vois pas beaucoup l'utilité d'avoir une compression de son code sur un raccourci clavier. De mon coté, j'utilise des outils comme sass pour compresser mon css pour la prod, ou des scripts comme grunt. Tu peux cependant utiliser le build system de sublime text pour arriver à un résultat équivalent.

[Voici un article](http://addyosmani.com/blog/custom-sublime-text-build-systems-for-popular-tools-and-languages/) que je trouve assez bien fait sur le sujet.

**Comment by NumEricR** [comment]
Ok merci pour le lien, je regarderais ça.
